services:
  postgres-db:
    container_name: inventory
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Inventory_Practice
    ports:
      - "5469:5432"