CREATE TABLE inventory
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_description       VARCHAR(255),
    qty                    INTEGER,
    cost                   DOUBLE PRECISION,
    date_of_last_inventory date,
    CONSTRAINT pk_inventory PRIMARY KEY (id)
);